version: "3.3"

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: ./api
    ports:
      - "3333:3333"
      - "5555:5555"
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads
  
  front:
    container_name: front
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  uploads:
    driver: local
    driver_opts:
      device: ${HOME}/uploads
      o: bind
      type: none