version: "3.3"

services:

  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./api
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - ./api/src:/app/src
  
  front:
    container_name: front
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./front/src:/app/src