version: "3.3"

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./api
    ports:
      - "3333:3333"
      - "5555:5555"
    depends_on:
      - db
  
  front:
    container_name: front
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres:
    driver: local
    driver_opts:
      device: ${HOME}/postgres
      o: bind
      type: none